---
title: "DIC-WAIC comparison"
output: pdf_document
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = normalizePath('..'))

```
```{r load, echo=FALSE, include=FALSE}
library(pander)
library(dplyr)
load(file = "Data/Rdata/DIC_ls.Rdata")
load(file = "Data/Rdata/waic_ls.Rdata")
mod_names <- c("model 1", "model 2", "model 3",
               "model 4", "model 5", "model 6")

# Until model 6 is fully run:
mod_names2 <- c("model 1", "model 2", "model 3",
               "model 4", "model 5")
```

DIC and WAIC values for each model. Table ranked from lowest to highest by value. Model 1 is least complex, model 5 is most complex
```{r dic}
# Produce DIC summary - output is penalized deviance
getPenDic <- function(x) sum(x$deviance) + sum(x$penalty)
modelDic <- function(z) (sapply(z, getPenDic))
summaryDic <- function(y) sapply(y, modelDic)
dic1 <- DIC_list %>%
  summaryDic() %>%
  data.frame() %>%
  `colnames<-` (mod_names)

dic_mean <- dic1 %>%
  colMeans() %>%
  data.frame() %>%
  dplyr::mutate(model = mod_names) %>%
  `colnames<-` (c("DIC", "model")) %>%
  arrange(DIC) %>%
  dplyr::select(model, DIC)
dic_mean$std <- sapply(dic1, sd)


```

```{r waic}
mean_waic_model <- function(x) (sapply(x, function(x) x$waic))
waic_summary <- function(x) sapply(x, mean_waic_model)
waic1 <- waic_list %>%
  waic_summary %>%
  data.frame() %>%
  `colnames<-`(mod_names2)

waic_mean <- waic1 %>%
  colMeans() %>%
  data.frame() %>%
  dplyr::mutate(model = mod_names2) %>%
  `colnames<-` (c("WAIC", "model")) %>%
  arrange(WAIC) %>%
  dplyr::select(model, WAIC)
waic_mean$std <- sapply(waic1, sd)


```

```{r table}

panderOptions('table.alignment.default',
  function(df)
     ifelse(sapply(df, is.character), 'left', 'right'))
pander(dic_mean)
pander(waic_mean)  
```
DIC values for each epidemic realization
```{r dic+print, echo = FALSE}
pander(dic1)
```
WAIC values for each epidemic realization
```{r waic_print, echo = FALSE}
pander(waic1)
```
