---
title: "Cholera transmission"
author: "Matthew"
date: "February 9, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

#1 Model
## 1.1 Model structure  
We constructed a series of nested models where the force of infection, $foi$, acting upon a neighborhood was composed of an external force of infection, $\alpha$, and an internal force of infection, $\beta$.   

From simple to complex we allowed (1) a single $\beta$ and single $\alpha$ for all neighborhoods, (2) an individual $\beta_{i}$ for each neighborhood and a single $\alpha$ for all neighborhoods, and (5) an individual $\beta_{i}$ for each neighborhood and a single asymmetric $\alpha_{i,j}$ for each neighborhood pair.  


Two additional models were constructed where we relaxed the contraints on the external forces of infection, $\alpha$. In model 2.1 allowed an individual $\beta_{i}$ and $\alpha_{i}$ for each neighborhood and in model 2.2 we allowed an individual $\beta_{i}$ for each neighborhood and symmetric $\alpha_{j,i}$ for each neighborhood pair ($\alpha_{j,i} = \alpha_{i,j}$). These models were not supported by the model selection process and were not reported in the main text.  

Each model was based upon the following construction:
$$^{new}\textrm{I}_{i,t+1}\sim Poisson(\lambda_{i,t})$$
$$\lambda_{i,t} = \frac{S_{i,t}\phi}{N_{i}} (\beta_{i}I_{i,t} + \sum_{j\neq i}\alpha_{j,i}I_{j,t} )$$

where:  
$^{new}\textrm{I}_{i,t}$ = the number of new infectious cases in each neighborhood $i$ at time $t$  
$I_{i,t}$ = the total number of infectious cases in each neighborhood $i$ at time $t$  
$S_{i,t}$ = the number of susceptible people in each neighborhood $i$ at time $t$  
$N_{i}$ = the total poulation of neighborhood $i$  
$\beta_{i}$ = the force of internal infection in neighborhood $i$  
$\alpha_{j,i}$ = the force of infection from neighborhood $j$ to neighborhood $i$.  


The total number of cases $I_{i,t}$ was updated via:
$$I_{i,t+1} = I_{i,t} + \frac{^{new}\textrm{I}_{i,t}}{\phi} - R_{i,t}$$  
where:  
$\phi$ = the fraction of cases that are reported  
$R_{i,t}$ = the number of people who recovered or died from infection.

The number of recovered individuals $R_{i,t}$ was updated via:  
$$R_{i,t} = \frac{1}{\gamma} I_{i,t}$$
where:  
$\gamma$ = the average duration of infectiousness (fixed at 5 days).  

The number of suceptibles $S_{i,t}$ was updated via:
$$S_{i,t+1} = S_{i,t} - \frac{^{new}\textrm{I}_{i,t}}{\phi}$$  

## 1.2 Hydraulic connectivity and geographic proximity  
To assess the effect of hyraulic connectivity (model 2b) we allowed the $foi$ between
two neighborhoods to vary depending on if the neighborhoods are connected via water pipes such that $$foi_{i,j} \begin{cases}
  \alpha & \text{ if no water connection } i \rightarrow j \\
  \alpha + \eta & \text{ if water connection } i \rightarrow j 
\end{cases}$$  

To incorporate geographic proximity (model 2c) we added an additional term $\kappa$ 
if the neighborhoods shared a border. The resulting $foi_{i,j}$ can be described as
$$foi_{i,j} \begin{cases}
  \alpha & \text{ if no shared border or water connection } i \rightarrow j \\
  \alpha + \eta & \text{ if no shared border but water connection } i \rightarrow j \text{ exists}\\
  \alpha + \eta +\kappa & \text{ if shared border and water connection } i \rightarrow j  \text{ exists}
\end{cases}$$  
The effect of water, $\eta$, and the effect of the shared border, $\kappa$, are not fitted to each neighborhood, but are shared citywide.

